version: '3'

volumes:
  elasticsearch:
    driver: local
  grafana:
    driver: local
  rabbitmq:
    driver: local

services:
  producer:
    build:
      context: ./producer

  telegraf:
    image: telegraf
    restart: always
    volumes:
    - ./telegraf:/etc/telegraf
    command:
    - --config
    - /etc/telegraf/config.toml
    ports:
    - "9273:9273"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    restart: always
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: '-Xms1024m -Xmx1024m'
    volumes:
    - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    restart: always
    ports:
    - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

  grafana:
    image: grafana/grafana
    restart: always
    ports:
    - "3000:3000"
    volumes:
    - grafana:/var/lib/grafana

  rabbitmq:
    image: rabbitmq:management
    restart: always
    hostname: rabbitmq
    env_file:
    - ./rabbitmq.env
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 512MiB
    volumes:
    - rabbitmq:/var/lib/rabbitmq/mnesia
    - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
    ports:
    - "15672:15672"
    - "5672:5672"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    restart: always
    volumes:
    - ./logstash/config:/usr/share/logstash/config
    - ./logstash/pipeline:/usr/share/logstash/pipeline
